### PR TITLE
Fix TypeError for Django 1.11

### LINKED ISSUE #11: TypeError with Django 1.11
The `render` method in `widgets.py` is broken in Django 1.11.

Indeed, this line 

```python
input_attrs = self.build_attrs(attrs, type=self.input_type, name=name)
```

uses the fact that the `build_attrs()` method is defined as such (Django 1.10) :

```python
    def build_attrs(self, extra_attrs=None, **kwargs):
        "Helper function for building an attribute dictionary."
        attrs = dict(self.attrs, **kwargs)
        if extra_attrs:
            attrs.update(extra_attrs)
        return attrs
```

However it has changed in Django 1.11 (see https://github.com/django/django/blob/stable/1.11.x/django/forms/widgets.py#L228) : 

```python
    def build_attrs(self, base_attrs, extra_attrs=None):
        "Helper function for building an attribute dictionary."
        attrs = base_attrs.copy()
        if extra_attrs is not None:
            attrs.update(extra_attrs)
        return attrs
```

### PR DESCRIPTION
**Pull request by Crocmagnon**
This fixes the issue for Django 1.11, however it won't work anymore with Django <= 1.10...

### CODE REVIEW

**Comment by Crocmagnon** [comment]
Sounds fair to me ! I don't know why I let pass the syntax error 😨

**Comment by samuelcolvin** [comment]
We're not using this library anymore but I'd be happy to merge this and deploy an up.

@Crocmagnon is there anything else required before doing a release to support dj 1.11?

**Comment by Crocmagnon** [comment]
Great!
@samuelcolvin, I don't think so, at least it worked for me. @jsbUSMC, do you have anything to add ?

**Comment by jsbUSMC** [comment]
I don't have anything to add, thank you @Crocmagnon !

**Comment by Crocmagnon** [comment]
@samuelcolvin, are you still ok for a merge ? :)

**Comment by samuelcolvin** [comment]
Sorry, yes Will do.

**Comment by samuelcolvin** [comment]
sorry for delay, merged and deployed https://pypi.python.org/pypi/django-bootstrap3-datetimepicker-2.

**Pull request merged**
